# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FollowUsers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, follow_id: int=None, follower: int=None, following: int=None, time: datetime=None):  # noqa: E501
        """FollowUsers - a model defined in Swagger

        :param follow_id: The follow_id of this FollowUsers.  # noqa: E501
        :type follow_id: int
        :param follower: The follower of this FollowUsers.  # noqa: E501
        :type follower: int
        :param following: The following of this FollowUsers.  # noqa: E501
        :type following: int
        :param time: The time of this FollowUsers.  # noqa: E501
        :type time: datetime
        """
        self.swagger_types = {
            'follow_id': int,
            'follower': int,
            'following': int,
            'time': datetime
        }

        self.attribute_map = {
            'follow_id': 'followID',
            'follower': 'follower',
            'following': 'following',
            'time': 'time'
        }
        self._follow_id = follow_id
        self._follower = follower
        self._following = following
        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'FollowUsers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FollowUsers of this FollowUsers.  # noqa: E501
        :rtype: FollowUsers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def follow_id(self) -> int:
        """Gets the follow_id of this FollowUsers.


        :return: The follow_id of this FollowUsers.
        :rtype: int
        """
        return self._follow_id

    @follow_id.setter
    def follow_id(self, follow_id: int):
        """Sets the follow_id of this FollowUsers.


        :param follow_id: The follow_id of this FollowUsers.
        :type follow_id: int
        """

        self._follow_id = follow_id

    @property
    def follower(self) -> int:
        """Gets the follower of this FollowUsers.


        :return: The follower of this FollowUsers.
        :rtype: int
        """
        return self._follower

    @follower.setter
    def follower(self, follower: int):
        """Sets the follower of this FollowUsers.


        :param follower: The follower of this FollowUsers.
        :type follower: int
        """

        self._follower = follower

    @property
    def following(self) -> int:
        """Gets the following of this FollowUsers.


        :return: The following of this FollowUsers.
        :rtype: int
        """
        return self._following

    @following.setter
    def following(self, following: int):
        """Sets the following of this FollowUsers.


        :param following: The following of this FollowUsers.
        :type following: int
        """

        self._following = following

    @property
    def time(self) -> datetime:
        """Gets the time of this FollowUsers.


        :return: The time of this FollowUsers.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this FollowUsers.


        :param time: The time of this FollowUsers.
        :type time: datetime
        """

        self._time = time
