# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class History(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, view_id: int=None, user_id: int=None, post_id: int=None, time_viewed: datetime=None):  # noqa: E501
        """History - a model defined in Swagger

        :param view_id: The view_id of this History.  # noqa: E501
        :type view_id: int
        :param user_id: The user_id of this History.  # noqa: E501
        :type user_id: int
        :param post_id: The post_id of this History.  # noqa: E501
        :type post_id: int
        :param time_viewed: The time_viewed of this History.  # noqa: E501
        :type time_viewed: datetime
        """
        self.swagger_types = {
            'view_id': int,
            'user_id': int,
            'post_id': int,
            'time_viewed': datetime
        }

        self.attribute_map = {
            'view_id': 'viewID',
            'user_id': 'userID',
            'post_id': 'postID',
            'time_viewed': 'timeViewed'
        }
        self._view_id = view_id
        self._user_id = user_id
        self._post_id = post_id
        self._time_viewed = time_viewed

    @classmethod
    def from_dict(cls, dikt) -> 'History':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The History of this History.  # noqa: E501
        :rtype: History
        """
        return util.deserialize_model(dikt, cls)

    @property
    def view_id(self) -> int:
        """Gets the view_id of this History.


        :return: The view_id of this History.
        :rtype: int
        """
        return self._view_id

    @view_id.setter
    def view_id(self, view_id: int):
        """Sets the view_id of this History.


        :param view_id: The view_id of this History.
        :type view_id: int
        """

        self._view_id = view_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this History.


        :return: The user_id of this History.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this History.


        :param user_id: The user_id of this History.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def post_id(self) -> int:
        """Gets the post_id of this History.


        :return: The post_id of this History.
        :rtype: int
        """
        return self._post_id

    @post_id.setter
    def post_id(self, post_id: int):
        """Sets the post_id of this History.


        :param post_id: The post_id of this History.
        :type post_id: int
        """

        self._post_id = post_id

    @property
    def time_viewed(self) -> datetime:
        """Gets the time_viewed of this History.


        :return: The time_viewed of this History.
        :rtype: datetime
        """
        return self._time_viewed

    @time_viewed.setter
    def time_viewed(self, time_viewed: datetime):
        """Sets the time_viewed of this History.


        :param time_viewed: The time_viewed of this History.
        :type time_viewed: datetime
        """

        self._time_viewed = time_viewed
