# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SavedComments(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, save_id: int=None, user_id: int=None, comment_id: int=None, time_saved: datetime=None):  # noqa: E501
        """SavedComments - a model defined in Swagger

        :param save_id: The save_id of this SavedComments.  # noqa: E501
        :type save_id: int
        :param user_id: The user_id of this SavedComments.  # noqa: E501
        :type user_id: int
        :param comment_id: The comment_id of this SavedComments.  # noqa: E501
        :type comment_id: int
        :param time_saved: The time_saved of this SavedComments.  # noqa: E501
        :type time_saved: datetime
        """
        self.swagger_types = {
            'save_id': int,
            'user_id': int,
            'comment_id': int,
            'time_saved': datetime
        }

        self.attribute_map = {
            'save_id': 'saveID',
            'user_id': 'userID',
            'comment_id': 'commentID',
            'time_saved': 'timeSaved'
        }
        self._save_id = save_id
        self._user_id = user_id
        self._comment_id = comment_id
        self._time_saved = time_saved

    @classmethod
    def from_dict(cls, dikt) -> 'SavedComments':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SavedComments of this SavedComments.  # noqa: E501
        :rtype: SavedComments
        """
        return util.deserialize_model(dikt, cls)

    @property
    def save_id(self) -> int:
        """Gets the save_id of this SavedComments.


        :return: The save_id of this SavedComments.
        :rtype: int
        """
        return self._save_id

    @save_id.setter
    def save_id(self, save_id: int):
        """Sets the save_id of this SavedComments.


        :param save_id: The save_id of this SavedComments.
        :type save_id: int
        """

        self._save_id = save_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this SavedComments.


        :return: The user_id of this SavedComments.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this SavedComments.


        :param user_id: The user_id of this SavedComments.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def comment_id(self) -> int:
        """Gets the comment_id of this SavedComments.


        :return: The comment_id of this SavedComments.
        :rtype: int
        """
        return self._comment_id

    @comment_id.setter
    def comment_id(self, comment_id: int):
        """Sets the comment_id of this SavedComments.


        :param comment_id: The comment_id of this SavedComments.
        :type comment_id: int
        """

        self._comment_id = comment_id

    @property
    def time_saved(self) -> datetime:
        """Gets the time_saved of this SavedComments.


        :return: The time_saved of this SavedComments.
        :rtype: datetime
        """
        return self._time_saved

    @time_saved.setter
    def time_saved(self, time_saved: datetime):
        """Sets the time_saved of this SavedComments.


        :param time_saved: The time_saved of this SavedComments.
        :type time_saved: datetime
        """

        self._time_saved = time_saved
