# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SavedPosts(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, save_id: int=None, user_id: int=None, post_id: int=None, time_saved: datetime=None):  # noqa: E501
        """SavedPosts - a model defined in Swagger

        :param save_id: The save_id of this SavedPosts.  # noqa: E501
        :type save_id: int
        :param user_id: The user_id of this SavedPosts.  # noqa: E501
        :type user_id: int
        :param post_id: The post_id of this SavedPosts.  # noqa: E501
        :type post_id: int
        :param time_saved: The time_saved of this SavedPosts.  # noqa: E501
        :type time_saved: datetime
        """
        self.swagger_types = {
            'save_id': int,
            'user_id': int,
            'post_id': int,
            'time_saved': datetime
        }

        self.attribute_map = {
            'save_id': 'saveID',
            'user_id': 'userID',
            'post_id': 'postID',
            'time_saved': 'timeSaved'
        }
        self._save_id = save_id
        self._user_id = user_id
        self._post_id = post_id
        self._time_saved = time_saved

    @classmethod
    def from_dict(cls, dikt) -> 'SavedPosts':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SavedPosts of this SavedPosts.  # noqa: E501
        :rtype: SavedPosts
        """
        return util.deserialize_model(dikt, cls)

    @property
    def save_id(self) -> int:
        """Gets the save_id of this SavedPosts.


        :return: The save_id of this SavedPosts.
        :rtype: int
        """
        return self._save_id

    @save_id.setter
    def save_id(self, save_id: int):
        """Sets the save_id of this SavedPosts.


        :param save_id: The save_id of this SavedPosts.
        :type save_id: int
        """

        self._save_id = save_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this SavedPosts.


        :return: The user_id of this SavedPosts.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this SavedPosts.


        :param user_id: The user_id of this SavedPosts.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def post_id(self) -> int:
        """Gets the post_id of this SavedPosts.


        :return: The post_id of this SavedPosts.
        :rtype: int
        """
        return self._post_id

    @post_id.setter
    def post_id(self, post_id: int):
        """Sets the post_id of this SavedPosts.


        :param post_id: The post_id of this SavedPosts.
        :type post_id: int
        """

        self._post_id = post_id

    @property
    def time_saved(self) -> datetime:
        """Gets the time_saved of this SavedPosts.


        :return: The time_saved of this SavedPosts.
        :rtype: datetime
        """
        return self._time_saved

    @time_saved.setter
    def time_saved(self, time_saved: datetime):
        """Sets the time_saved of this SavedPosts.


        :param time_saved: The time_saved of this SavedPosts.
        :type time_saved: datetime
        """

        self._time_saved = time_saved
