# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SubscribedCommunities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription_id: int=None, user_id: int=None, community_id: int=None, time_subscribed: datetime=None):  # noqa: E501
        """SubscribedCommunities - a model defined in Swagger

        :param subscription_id: The subscription_id of this SubscribedCommunities.  # noqa: E501
        :type subscription_id: int
        :param user_id: The user_id of this SubscribedCommunities.  # noqa: E501
        :type user_id: int
        :param community_id: The community_id of this SubscribedCommunities.  # noqa: E501
        :type community_id: int
        :param time_subscribed: The time_subscribed of this SubscribedCommunities.  # noqa: E501
        :type time_subscribed: datetime
        """
        self.swagger_types = {
            'subscription_id': int,
            'user_id': int,
            'community_id': int,
            'time_subscribed': datetime
        }

        self.attribute_map = {
            'subscription_id': 'subscriptionID',
            'user_id': 'userID',
            'community_id': 'communityID',
            'time_subscribed': 'timeSubscribed'
        }
        self._subscription_id = subscription_id
        self._user_id = user_id
        self._community_id = community_id
        self._time_subscribed = time_subscribed

    @classmethod
    def from_dict(cls, dikt) -> 'SubscribedCommunities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubscribedCommunities of this SubscribedCommunities.  # noqa: E501
        :rtype: SubscribedCommunities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_id(self) -> int:
        """Gets the subscription_id of this SubscribedCommunities.


        :return: The subscription_id of this SubscribedCommunities.
        :rtype: int
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id: int):
        """Sets the subscription_id of this SubscribedCommunities.


        :param subscription_id: The subscription_id of this SubscribedCommunities.
        :type subscription_id: int
        """

        self._subscription_id = subscription_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this SubscribedCommunities.


        :return: The user_id of this SubscribedCommunities.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this SubscribedCommunities.


        :param user_id: The user_id of this SubscribedCommunities.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def community_id(self) -> int:
        """Gets the community_id of this SubscribedCommunities.


        :return: The community_id of this SubscribedCommunities.
        :rtype: int
        """
        return self._community_id

    @community_id.setter
    def community_id(self, community_id: int):
        """Sets the community_id of this SubscribedCommunities.


        :param community_id: The community_id of this SubscribedCommunities.
        :type community_id: int
        """

        self._community_id = community_id

    @property
    def time_subscribed(self) -> datetime:
        """Gets the time_subscribed of this SubscribedCommunities.


        :return: The time_subscribed of this SubscribedCommunities.
        :rtype: datetime
        """
        return self._time_subscribed

    @time_subscribed.setter
    def time_subscribed(self, time_subscribed: datetime):
        """Sets the time_subscribed of this SubscribedCommunities.


        :param time_subscribed: The time_subscribed of this SubscribedCommunities.
        :type time_subscribed: datetime
        """

        self._time_subscribed = time_subscribed
