# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Votes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, post_vote_id: int=None, user_id: int=None, post_id: int=None, voted: bool=None, time: datetime=None):  # noqa: E501
        """Votes - a model defined in Swagger

        :param post_vote_id: The post_vote_id of this Votes.  # noqa: E501
        :type post_vote_id: int
        :param user_id: The user_id of this Votes.  # noqa: E501
        :type user_id: int
        :param post_id: The post_id of this Votes.  # noqa: E501
        :type post_id: int
        :param voted: The voted of this Votes.  # noqa: E501
        :type voted: bool
        :param time: The time of this Votes.  # noqa: E501
        :type time: datetime
        """
        self.swagger_types = {
            'post_vote_id': int,
            'user_id': int,
            'post_id': int,
            'voted': bool,
            'time': datetime
        }

        self.attribute_map = {
            'post_vote_id': 'postVoteID',
            'user_id': 'userID',
            'post_id': 'postID',
            'voted': 'voted',
            'time': 'time'
        }
        self._post_vote_id = post_vote_id
        self._user_id = user_id
        self._post_id = post_id
        self._voted = voted
        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'Votes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Votes of this Votes.  # noqa: E501
        :rtype: Votes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def post_vote_id(self) -> int:
        """Gets the post_vote_id of this Votes.


        :return: The post_vote_id of this Votes.
        :rtype: int
        """
        return self._post_vote_id

    @post_vote_id.setter
    def post_vote_id(self, post_vote_id: int):
        """Sets the post_vote_id of this Votes.


        :param post_vote_id: The post_vote_id of this Votes.
        :type post_vote_id: int
        """

        self._post_vote_id = post_vote_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Votes.


        :return: The user_id of this Votes.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Votes.


        :param user_id: The user_id of this Votes.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def post_id(self) -> int:
        """Gets the post_id of this Votes.


        :return: The post_id of this Votes.
        :rtype: int
        """
        return self._post_id

    @post_id.setter
    def post_id(self, post_id: int):
        """Sets the post_id of this Votes.


        :param post_id: The post_id of this Votes.
        :type post_id: int
        """

        self._post_id = post_id

    @property
    def voted(self) -> bool:
        """Gets the voted of this Votes.


        :return: The voted of this Votes.
        :rtype: bool
        """
        return self._voted

    @voted.setter
    def voted(self, voted: bool):
        """Sets the voted of this Votes.


        :param voted: The voted of this Votes.
        :type voted: bool
        """

        self._voted = voted

    @property
    def time(self) -> datetime:
        """Gets the time of this Votes.


        :return: The time of this Votes.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this Votes.


        :param time: The time of this Votes.
        :type time: datetime
        """

        self._time = time
